채팅 구현
connection-2023/frontend pull request #344
Opened 2024-03-29 09:13 UTC by hyeonjun-L

## Summary
채팅 구현

## PR 타입

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

### 관련 이슈: 이슈 번호

close #316 
  
## 변경사항(작업 목록)

> ## 소켓
> socket.io-client 설치
> SocketInitializer 컴포넌트 (소켓 연결 및 소켓 이벤트 관리 컴포넌트 구현) 
```추후 로그인 새로고침으로 변환 시 의존성 배열 userType 제거```
> useSocketStore 소켓 관련 store 구현

> ## react-query
> react-query devtools 설치
> queryClient 401 에러 시 자동 토큰 재발급 및 쿼리 재요청 처리 구현 (d16dbb0d1f25c03b501c263ec9f58a131432420c)

> ## 채팅
> 공통 컴포넌트 채팅 버튼 (ChatButton) 구현
> 채팅 모달 크기 및 위치 드래그 동적 변경 기능 구현
>  채팅방 (조회, 생성, 나가기), 채팅(조회, 생성, 읽기) 등 api연결 및 기능 구현
> 모든 채팅 api 낙관적으로 한번만 동작 하도록 구현(react-query cache)
>  상대 현재 활동 api 연결 및 기능 구현
>  chatStore 채팅 관련 store 구현
>  useChatsQuery 채팅 무한 스크롤 훅 구현
> 채팅 모든 api 에러 핸들링 및 로딩 처리 완료 

> ## etc
> 강사 및 유저 전환 새로고침으로 변환
> useIntersect 훅 렌더링 최적화
> dateTimeUtils 오후 오전 시간대 함수 추가

2024-04-01 09:08 UTC, Eunseo-jo requested changes
소켓 연결하느라 고생하셨습니당 코멘트 확인 부탁🙇‍♀️

2024-04-01 09:08 UTC, Eunseo-jo commented on src/types/chat.d.ts
> +        };
```suggestion
        {
          userId: number | null;
          lecturerId: number | null;
        }
```
이렇게 하는 건 어떠신가요오👀 (`receiver`도..)

2024-04-01 09:08 UTC, Eunseo-jo commented on src/types/chat.d.ts
> +  createdAt: Data;
`Data` 타입 어디에서 가져온 것일까요오?

2024-04-01 09:08 UTC, Eunseo-jo commented on src/lib/apis/chatApi.ts
> +    // const resData = await response.json();
```suggestion
```

2024-04-01 09:08 UTC, Eunseo-jo commented on src/lib/apis/chatApi.ts
> +        };
```suggestion
    const { data } = await response.json();
    const { lecturerProfile, user } = data;
    
    const id = lecturerProfile.id || user.id;
    const nickname = lecturerProfile.nickname || user.nickname;
    const profileImg = lecturerProfileImageUrl[0].url || userProfileImage?.imageUrl;
    
    return { id, nickname, profileImg }
```
요 방법이 좀 더 가독성 좋을거 같습니당 
`profilImg` -> `profileImg` 오타 발견👀

2024-04-01 09:08 UTC, Eunseo-jo commented on src/lib/apis/classApi.ts
> +      }
404일 때 에러 띄우면서 리턴 값이 왜 필요한건가욤?!

2024-04-01 09:08 UTC, Eunseo-jo commented on src/app/layout.tsx
> +          <ReactQueryDevtools initialIsOpen={false} />
layout에 추가할 게 아니라 `src/lib/provider/providers.tsx`에 추가해주세욤
[참고](https://tanstack.com/query/latest/docs/framework/react/examples/nextjs-suspense-streaming)

2024-04-01 09:08 UTC, Eunseo-jo commented on src/app/_components/chat/Chat.tsx
> +      }
```suggestion
      {
        content?: string;
        imageUrl?: string;
        error: boolean;
      }
```
요렇게 해도 되지 않을지..?

2024-04-01 09:08 UTC, Eunseo-jo commented on src/app/_components/chat/Chat.tsx
> +  };
`date-fns`에 `isSameDay` 쓰면 더 편리할 거 같아여

2024-04-01 09:08 UTC, Eunseo-jo commented on src/app/_components/chat/Chat.tsx
> +                ) : null}
```suggestion
                { content && content }
                { imageUrl && 
                  <Image
                    width={261}
                    height={167}
                    src={imageUrl}
                    alt="커넥션 채팅 이미지"
                  />
             }
```
삼항 연산자 안에 삼항 연산자라 이게 더 좋을 듯 하네욤

2024-04-01 09:08 UTC, Eunseo-jo commented on src/app/_components/chat/ChatRoomMain.tsx
> +    | null
이거 중복 코드 같은데 type으로 분리해서 재사용하는 게 좋을거 같아용

2024-04-01 09:08 UTC, Eunseo-jo commented on src/app/_components/Header/NotificationIndicator.tsx
> +        {chat.imageUrl ? '이미지' : chat.content}
`'이미지'` 이거 왜 때문에 필요한 것일까요오

2024-04-01 12:43 UTC, hyeonjun-L commented on src/app/_components/Header/NotificationIndicator.tsx
> +        {chat.imageUrl ? '이미지' : chat.content}
채팅 내용이 이미지가 왔을 때 이미지 url을 표시하는 게 아닌 이미지가 왔다는 걸 표시하기 위함입니다~

2024-04-01 12:43 UTC, hyeonjun-L commented on src/app/_components/chat/Chat.tsx
> +      }
타입을 조금 더 타이트하게 하려고 위처럼 진행 했어
해당 변수 content 혹은 imageUrl 둘 중 하나는 포함 되어야 해서 위 처럼 타입 지정 했어
제안해준 타입은 둘 다 포함 되지 않을 수 있응께~!

2024-04-01 12:43 UTC, hyeonjun-L commented on src/app/_components/chat/Chat.tsx
> +  };
오오 아리가또 👍  바로 반영 할게

2024-04-01 12:43 UTC, hyeonjun-L commented on src/app/_components/chat/Chat.tsx
> +                ) : null}
그러게 한번 더 봐볼껄 고마우이 💯 하기 코드로 변경 해볼게
```js
                {content ||
                  (imageUrl && (
                    <Image
                      width={261}
                      height={167}
                      src={imageUrl}
                      alt="커넥션 채팅 이미지"
                    />
                  ))}
```

2024-04-01 12:43 UTC, hyeonjun-L commented on src/app/_components/chat/ChatRoomMain.tsx
> +    | null
그러네 고마워 반영할게 👍

2024-04-01 12:43 UTC, hyeonjun-L commented on src/app/layout.tsx
> +          <ReactQueryDevtools initialIsOpen={false} />
컨벤션 때문에 그런거야? 일단은 반영 했어, 그리고 추후에 Providers => reactQueryProviders 이런식으로 바꾸는게 좋을듯
그게 아니라면 provider 추가 할일 생기면 ```Providers```에 추가할까?

2024-04-01 12:43 UTC, hyeonjun-L commented on src/lib/apis/chatApi.ts
> +        };
오케이 고마워 반영 할게 👍

2024-04-01 12:43 UTC, hyeonjun-L commented on src/lib/apis/classApi.ts
> +      }
백엔드에서 해당 데이터 없으면 404를 반환 하는데 에러처리가 되면 안돼서 리턴 진행 하는중이여라~

2024-04-01 12:43 UTC, hyeonjun-L commented on src/types/chat.d.ts
> +        };
상기 답글처럼 타입 더 엄격하게 진행을 위함이요오

2024-04-01 12:43 UTC, hyeonjun-L commented on src/types/chat.d.ts
> +  createdAt: Data;
오타입니다 정정 할게 👍

2024-04-03 11:21 UTC, Eunseo-jo commented on src/app/layout.tsx
> +          <ReactQueryDevtools initialIsOpen={false} />
React-Query 관련 설정을 한 곳에서 하는 것이 좋을꺼 같아서!
`reactQueryProviders`로 변경하는 거 좋습니다 굿굿

2024-04-03 11:23 UTC, Eunseo-jo approved these changes
리뷰 반영 좋아여👍 고생하셨습니당

2024-04-03 11:23 UTC, merged