지도 기능 추가 및 리팩토링
connection-2023/frontend pull request #347
Opened 2024-04-02 10:49 UTC by hyeonjun-L

## Summary

지도 기능 추가 및 리팩토링

## PR 타입

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

### 관련 이슈: 이슈 번호

close #345
  
## 변경사항(작업 목록)

> ## 기능 추가 
> 협의 후 결정 지도 구현 및 퍼블리싱
> VWORLD 공공 데이터 api 연결 (지역 polyline ,주소 좌표)

> ## 리팩토링
> 지도 주소 좌표 안나왔을 때 예외처리
> production 환경 지도 조건문 변경
> 지도 에러 및 로딩 처리
> 코드 간결화 및 InfoWindow 닫히는 버그 해결
> NaverMapProvider root로 이동

2024-04-03 11:35 UTC, Eunseo-jo requested changes
리뷰랑 파일 충돌 확인해주세요 :)

2024-04-03 11:35 UTC, Eunseo-jo commented on src/components/Map/AreaHighlightMap.tsx
> +          acc: { [kye: string]: string[] },
```suggestion
          acc: { [key: string]: string[] },
```
key는 오타일까요...?..

2024-04-03 11:35 UTC, Eunseo-jo commented on src/components/Map/AddressMap.tsx
> +  const destinationLink = `https://map.naver.com/p/directions/-/${x},${y},${studioName}/-/transit?c=17.56,0,0,0,dh`;
여기 부분에서 CORS 오류 발생 가능성이 있을 거 같은데 문제 없나용?

2024-04-03 11:35 UTC, Eunseo-jo commented on src/app/api/map/polyline/route.ts
> +    `https://api.vworld.kr/req/data?service=data&version=2.0&request=GetFeature&format=json&errorformat=json&size=1000&page=1&data=${dataType}&attrFilter=${filterOption}:like:${query}&crs=EPSG:4326&k
도메인 주소의 쿼리 부분을 환경 변수로 설정하여 도메인 주소 변경 가능성을 고려하는 것이 좋을거 같습니당!

2024-04-04 06:25 UTC, merged

2024-04-04 06:32 UTC, hyeonjun-L commented on src/components/Map/AddressMap.tsx
> +  const destinationLink = `https://map.naver.com/p/directions/-/${x},${y},${studioName}/-/transit?c=17.56,0,0,0,dh`;
리소스 받아오는게 아니라서 상관 없으

2024-04-04 06:32 UTC, hyeonjun-L commented on src/app/api/map/polyline/route.ts
> +    `https://api.vworld.kr/req/data?service=data&version=2.0&request=GetFeature&format=json&errorformat=json&size=1000&page=1&data=${dataType}&attrFilter=${filterOption}:like:${query}&crs=EPSG:4326&k
const로 상수화 할게