클래스 수정 정기 클래스 추가 구현 및 리팩토링
connection-2023/frontend pull request #348
Opened 2024-04-05 15:29 UTC by Eunseo-jo

## Summary
클래스 수정 정기 클래스 추가 구현 및 리팩토링

## PR 타입

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

### 관련 이슈: 이슈 번호
- closed #342 
  
## 변경사항(작업 목록)
- 로딩 레이아웃 변경
- 사이드바 `activeSection` 로직 리팩토링
- 각 섹션 컴포넌트 분리
- 정기 클래스 case 추가 구현
- 메타 데이터 추가

2024-04-06 06:14 UTC, hyeonjun-L requested changes
고생 했어 👍 💯 🥇

2024-04-06 06:14 UTC, hyeonjun-L commented on src/app/class/[id]/edit/_components/plan/EditClassRange.tsx
> +  const [toValue, setToValue] = useState<string>(defaultValue.endDate);
```suggestion
  const [toValue, setToValue] = useState(defaultValue.endDate);
```

2024-04-06 06:14 UTC, hyeonjun-L commented on src/app/class/[id]/edit/_lib/addScheduleUtils.ts
> +  );
해당 부분 원데이 클래스 수정 에러 발생합니다 test class Id = 210

 다른 섹션 수정(스케줄 수정 안했을때)  

``` Cannot read properties of undefined (reading 'forEach')```
```schedule.dateTime```이 ```undefind``` 라서 ```calculateFinalDates``` 내부 하기 부분에서 에러 발생 합니다. 확인 한번 해주세요.


```js
 else {
    // 특정 날짜 선택 시
    const dateTimeSchedules = schedules as IDateTimeList[];

    return dateTimeSchedules.reduce((acc: Date[], schedule) => {
      schedule.dateTime.forEach((time) => {
        const newDate = makeNewDate(new Date(schedule.date), time);
        acc.push(newDate);
      });

      return acc;
    }, []);
  }
```

2024-04-06 06:14 UTC, hyeonjun-L commented on src/app/class/[id]/edit/page.tsx
>        };
클래스 수정 오류 ```Error: property daySchedules should not exist```

마찬가지로 원데이에서 해당 에러 발생합니다.
백엔드 api 명세서에는 ```daySchedules```이 없는데 확인 부탁드립니다.

reqData 이미지
![image](https://github.com/connection-2023/frontend/assets/113358733/2ad3eb3e-cfe4-4db7-b19e-f8f838abc973)

2024-04-06 06:14 UTC, hyeonjun-L commented on src/app/class/[id]/edit/_components/plan/index.tsx
> +        }}
유의 사항 필수 값 맞나? 아니면 지워주세요

2024-04-06 13:19 UTC, Eunseo-jo commented on src/app/class/[id]/edit/page.tsx
>        };
요건 백에서 아직 구현중이라고 합니당

2024-04-08 08:06 UTC, hyeonjun-L approved these changes

2024-04-08 08:06 UTC, merged